Repository 0xMiden/miden-client, pull requests merged in 2025-04, with the labels that each got.

#829 fix: flaky tests
  crates/rust-client/src/store/sqlite_store/sync.rs
  crates/rust-client/src/sync/mod.rs
  tests/integration/common.rs
Labels: no changelog

#832 fix: tests build
  .config/nextest.toml
  Makefile
  crates/web-client/package-lock.json
  crates/web-client/test/mocha.global.setup.mjs
  crates/web-client/yarn.lock
  tests/integration/main.rs
Labels: no changelog

#838 test: nested foreign procedure invocation
  tests/integration/fpi_tests.rs
Labels: no changelog

#841 fix: Makefile after changes on `miden-base`
  Makefile
Labels: no changelog

#845 chore: Update dependencies
  Cargo.lock
  crates/rust-client/Cargo.toml
  crates/rust-client/src/rpc/generated/nostd/rpc.rs
  crates/rust-client/src/rpc/generated/std/rpc.rs
Labels: no changelog

#846 fix: support final forward slash in endpoint
  crates/rust-client/src/rpc/endpoint.rs
Labels: no changelog

#847 refactor: `TonicRpcClient` improvements
  crates/rust-client/src/rpc/errors.rs
  crates/rust-client/src/rpc/tonic_client/api_client.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
Labels: no changelog

#859 chore: Move to base's next
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/src/tests.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/rpc/domain/account.rs
  crates/rust-client/src/rpc/generated/nostd/requests.rs
  crates/rust-client/src/rpc/generated/nostd/responses.rs
  crates/rust-client/src/rpc/generated/nostd/transaction.rs
  crates/rust-client/src/rpc/generated/std/requests.rs
  crates/rust-client/src/rpc/generated/std/responses.rs
  crates/rust-client/src/rpc/generated/std/transaction.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/foreign.rs
  crates/web-client/package-lock.json
  crates/web-client/yarn.lock
Labels: documentation, no changelog

#863 chore: update prover init in makefile
  Makefile
Labels: no changelog

#861 refactor: print enclosed error message for `ClientError::RecencyCondtionError`
  crates/rust-client/src/errors.rs
Labels: no changelog

#865 chore: add check for documentation changes in CI
  .github/workflows/docs.yml
  scripts/check-docs.sh
Labels: no changelog, no docs

#866 feat: read serialized note details
  crates/rust-client/src/rpc/tonic_client/mod.rs
Labels: no changelog, no docs

#871 feat: remove network from CliConfig
  bin/miden-cli/src/commands/account.rs
  bin/miden-cli/src/commands/init.rs
  bin/miden-cli/src/config.rs
  crates/rust-client/src/rpc/endpoint.rs
Labels: no changelog, no docs

#870 chore: Use TOML instead of JSON for exec input files.
  CHANGELOG.md
  Cargo.lock
  bin/miden-cli/Cargo.toml
  bin/miden-cli/src/commands/exec.rs
  bin/miden-cli/src/tests.rs
  bin/miden-cli/tests/files/test_cli_advice_inputs_expect_failure.masm
  bin/miden-cli/tests/files/test_cli_advice_inputs_expect_success.masm
  bin/miden-cli/tests/files/test_cli_advice_inputs_input.toml
Labels: no docs
