Repository 0xMiden/miden-client, pull requests merged in 2025-09, with the labels that each got.

#1218 chore: add generated JS files
  .prettierignore
  .typos.toml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rust-client/README.md
  crates/rust-client/src/store/web_store/.gitignore
  crates/rust-client/src/store/web_store/js/accounts.d.ts
  crates/rust-client/src/store/web_store/js/accounts.js
  crates/rust-client/src/store/web_store/js/accounts.js.map
  crates/rust-client/src/store/web_store/js/chainData.js
  crates/rust-client/src/store/web_store/js/chainData.js.map
  crates/rust-client/src/store/web_store/js/eslint.config.mjs
  crates/rust-client/src/store/web_store/js/eslint.config.mjs.map
  crates/rust-client/src/store/web_store/js/export.js
  crates/rust-client/src/store/web_store/js/export.js.map
  crates/rust-client/src/store/web_store/js/import.js
  crates/rust-client/src/store/web_store/js/import.js.map
  crates/rust-client/src/store/web_store/js/notes.js
  crates/rust-client/src/store/web_store/js/notes.js.map
  crates/rust-client/src/store/web_store/js/schema.d.ts
  crates/rust-client/src/store/web_store/js/schema.js
  crates/rust-client/src/store/web_store/js/schema.js.map
  crates/rust-client/src/store/web_store/js/sync.js
  crates/rust-client/src/store/web_store/js/sync.js.map
  crates/rust-client/src/store/web_store/js/transactions.js
  crates/rust-client/src/store/web_store/js/transactions.js.map
  crates/rust-client/src/store/web_store/js/utils.js
  crates/rust-client/src/store/web_store/js/utils.js.map
  docs/src/library.md
Labels: no docs

#1219 refactor: remove integration tests proc macro
  CHANGELOG.md
  Cargo.lock
  bin/integration-tests/Cargo.toml
  bin/integration-tests/README.md
  bin/integration-tests/build.rs
  bin/integration-tests/src/generated_tests.rs
  bin/integration-tests/src/tests/client.rs
  bin/integration-tests/src/tests/custom_transaction.rs
  bin/integration-tests/src/tests/fpi.rs
  bin/integration-tests/src/tests/network_transaction.rs
  bin/integration-tests/src/tests/onchain.rs
  bin/integration-tests/src/tests/swap_transaction.rs
  bin/integration-tests/test-case-marker/Cargo.toml
  bin/integration-tests/test-case-marker/src/lib.rs
Labels: no docs

#1252 ci: remove docs check
  .github/workflows/docs.yml
  scripts/check-docs.sh
Labels: no changelog

#1246 chore: move shared code into constants
  bin/integration-tests/build.rs
Labels: no changelog, no docs

#1243 chore: replace `NoteBuilder` by manually constructing the note
  bin/integration-tests/src/tests/network_transaction.rs
  crates/rust-client/Cargo.toml
Labels: no changelog, no docs, bypass-sdk-version-bump

#1259 chore: remove redundant `Send` bound
  crates/rust-client/src/builder.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/sync/state_sync.rs
Labels: no changelog, no docs, bypass-sdk-version-bump

#1212 tests: test webkit with playwright
  .github/workflows/test.yml
  Makefile
  crates/rust-client/src/store/web_store/js/accounts.js
  crates/rust-client/src/store/web_store/js/accounts.js.map
  crates/rust-client/src/store/web_store/js/chainData.js
  crates/rust-client/src/store/web_store/js/chainData.js.map
  crates/rust-client/src/store/web_store/js/notes.js
  crates/rust-client/src/store/web_store/js/notes.js.map
  crates/rust-client/src/store/web_store/js/sync.js
  crates/rust-client/src/store/web_store/js/sync.js.map
  crates/rust-client/src/store/web_store/js/transactions.js
  crates/rust-client/src/store/web_store/js/transactions.js.map
  crates/rust-client/src/store/web_store/ts/accounts.ts
  crates/rust-client/src/store/web_store/ts/chainData.ts
  crates/rust-client/src/store/web_store/ts/notes.ts
  crates/rust-client/src/store/web_store/ts/schema.ts
  crates/rust-client/src/store/web_store/ts/sync.ts
  crates/rust-client/src/store/web_store/ts/transactions.ts
  crates/web-client/package.json
  crates/web-client/playwright.config.ts
  eslint.config.js
Labels: no changelog, no docs

#1269 chore: bump dependencies
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/integration-tests/src/tests/custom_transaction.rs
  bin/integration-tests/src/tests/fpi.rs
  bin/miden-cli/Cargo.toml
  crates/rust-client/Cargo.toml
  crates/web-client/Cargo.toml
  crates/web-client/package.json
Labels: no docs

#1254 feat: Add a mutable getter for `TransactionRequest`'s advice map
  CHANGELOG.md
  crates/rust-client/src/transaction/request/mod.rs
Labels: no docs, bypass-sdk-version-bump

#1283 fix: update miden base
  Cargo.lock
  Cargo.toml
  bin/integration-tests/src/main.rs
  bin/integration-tests/src/tests/client.rs
  bin/integration-tests/src/tests/fpi.rs
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/rpc/domain/account.rs
  crates/rust-client/src/rpc/domain/nullifier.rs
  crates/rust-client/src/rpc/endpoint.rs
  crates/rust-client/src/rpc/generated/nostd/account.rs
  crates/rust-client/src/rpc/generated/nostd/note.rs
  crates/rust-client/src/rpc/generated/nostd/rpc.rs
  crates/rust-client/src/rpc/generated/nostd/rpc_store.rs
  crates/rust-client/src/rpc/generated/std/account.rs
  crates/rust-client/src/rpc/generated/std/note.rs
  crates/rust-client/src/rpc/generated/std/rpc.rs
  crates/rust-client/src/rpc/generated/std/rpc_store.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/data_store.rs
  crates/rust-client/src/store/errors.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/store/sqlite_store/merkle_store.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/sync/state_sync.rs
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/foreign.rs
  crates/web-client/src/models/account_id.rs
  crates/web-client/src/models/address.rs
  crates/web-client/src/models/executed_transaction.rs
  crates/web-client/test/fpi.test.ts
  docs/src/design.md
Labels: no changelog, bypass-sdk-version-bump

#1297 chore: re-export all auth components from miden-lib
  CHANGELOG.md
  crates/rust-client/src/account/mod.rs
Labels: no docs, bypass-sdk-version-bump

#1314 chore: patch v0.11.6
  CHANGELOG.md
  Cargo.lock
Labels: no docs

#1329 Reverting some lost changes from #1253
  crates/idxdb-store/src/.gitignore
  crates/idxdb-store/src/tsconfig.tsbuildinfo
  crates/web-client/js/index.js
  crates/web-client/js/types/index.d.ts
  crates/web-client/package.json
Labels: no changelog

#1322 fix: include current block in note import check
  crates/rust-client/src/note/import.rs
Labels: no changelog

#1287 feat: separate `migrations` and `settings` tables
  CHANGELOG.md
  bin/miden-cli/src/commands/account.rs
  bin/miden-cli/src/commands/import.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/config.rs
  bin/miden-cli/src/info.rs
  bin/miden-cli/src/utils.rs
  crates/idxdb-store/src/lib.rs
  crates/idxdb-store/src/mod.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/settings/mod.rs
  crates/rust-client/src/store/mod.rs
  crates/sqlite-store/src/db_management/errors.rs
  crates/sqlite-store/src/db_management/utils.rs
  crates/sqlite-store/src/lib.rs
  crates/sqlite-store/src/store.sql
  crates/web-client/yarn.lock
Labels: bypass-sdk-version-bump

#1355 chore: merge main to next
  CHANGELOG.md
  crates/web-client/package.json
  crates/web-client/src/models/address.rs
  docs/src/web-client/api/classes/Address.md
Labels: no changelog, no docs
