Repository 0xMiden/miden-client, pull requests merged in 2025-05, with the labels that each got.

#874 feat: update rusqlite version, add manager
  Cargo.lock
  crates/rust-client/Cargo.toml
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/store/sqlite_store/chain_data.rs
  crates/rust-client/src/store/sqlite_store/db_management/errors.rs
  crates/rust-client/src/store/sqlite_store/db_management/mod.rs
  crates/rust-client/src/store/sqlite_store/db_management/pool_manager.rs
  crates/rust-client/src/store/sqlite_store/db_management/utils.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/store/sqlite_store/note.rs
  crates/rust-client/src/store/sqlite_store/store.sql
  crates/rust-client/src/store/sqlite_store/sync.rs
  crates/rust-client/src/store/sqlite_store/transaction.rs
Labels: no changelog, no docs

#894 chore: update dependencies
  CHANGELOG.md
  Cargo.lock
  crates/rust-client/Cargo.toml
  crates/rust-client/src/mock.rs
  crates/rust-client/src/rpc/generated/nostd/responses.rs
  crates/rust-client/src/rpc/generated/std/responses.rs
  crates/rust-client/src/store/data_store.rs
  crates/rust-client/src/store/errors.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/store/sqlite_store/chain_data.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/store/sqlite_store/store.sql
  crates/rust-client/src/store/sqlite_store/sync.rs
  crates/rust-client/src/store/web_store/chain_data/js_bindings.rs
  crates/rust-client/src/store/web_store/chain_data/mod.rs
  crates/rust-client/src/store/web_store/chain_data/models.rs
  crates/rust-client/src/store/web_store/chain_data/utils.rs
  crates/rust-client/src/store/web_store/js/chainData.js
  crates/rust-client/src/store/web_store/js/schema.js
  crates/rust-client/src/store/web_store/js/sync.js
  crates/rust-client/src/store/web_store/mod.rs
  crates/rust-client/src/store/web_store/sync/js_bindings.rs
  crates/rust-client/src/store/web_store/sync/mod.rs
  crates/rust-client/src/sync/block_header.rs
  crates/rust-client/src/tests.rs
Labels: no docs

#888 refactor: lock account check
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/store/sqlite_store/sync.rs
  crates/rust-client/src/store/web_store/account/mod.rs
  crates/rust-client/src/store/web_store/sync/mod.rs
Labels: no changelog, no docs

#883 test: add token symbol map test and documentation
  bin/miden-cli/src/tests.rs
  docs/src/cli-config.md
Labels: no changelog

#890 chore: Replace `dead_code` with intended usage.
  crates/rust-client/src/rpc/domain/account.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/web_store/chain_data/mod.rs
Labels: no changelog, no docs

#909 fix: update `miden-base` in client
  Cargo.lock
  Makefile
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/foreign.rs
  crates/rust-client/src/transaction/request/mod.rs
  tests/integration/fpi_tests.rs
Labels: no changelog, no docs

#896 chore: Update links and references
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  LICENSE
  Makefile
  README.md
  bin/miden-cli/src/utils.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/lib.rs
  crates/rust-client/src/store/web_store/chain_data/mod.rs
  crates/web-client/README.md
  crates/web-client/package.json
  docs/book.toml
  docs/src/cli-config.md
  docs/src/get-started/create-account-use-faucet.md
  docs/src/get-started/p2p-private.md
  docs/src/get-started/p2p-public.md
  docs/src/library.md
  docs/src/web-client/examples/new-transactions.md
  docs/src/web-client/index.md
  scripts/configure-sandbox.sh
Labels: no changelog

#911 fix: update node branch
  Makefile
Labels: no changelog, no docs

#906 Improve Web Client Publishing Flow on Next Branch
  .github/workflows/enforce-web-client-version-bump.yml
  .github/workflows/publish-web-client-next.yml
  CHANGELOG.md
  Cargo.lock
  scripts/detect-web-client-changes.sh
Labels: no docs

#875 feat: node builder lib
  .github/workflows/test.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/src/tests.rs
  crates/node-builder/Cargo.toml
  crates/node-builder/README.md
  crates/node-builder/examples/simple.rs
  crates/node-builder/src/lib.rs
  crates/node-builder/src/main.rs
  crates/rust-client/src/store/mod.rs
  scripts/start-node.sh
  tests/integration/common.rs
Labels: no changelog, no docs

#915 Merge `main` into `next`
  .github/workflows/web-docs-check.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  bin/miden-cli/README.md
  crates/rust-client/src/rpc/domain/account.rs
  crates/rust-client/src/store/web_store/chain_data/mod.rs
  crates/web-client/package-lock.json
  crates/web-client/package.json
  crates/web-client/src/import.rs
  crates/web-client/src/new_account.rs
  crates/web-client/test/import.test.ts
  crates/web-client/test/new_account.test.ts
  crates/web-client/test/webClientTestUtils.ts
  crates/web-client/yarn.lock
  docs/src/install-and-run.md
  docs/src/web-client/api/classes/WebClient.md
Labels: no docs

#901 refactor: `TransactionRequestBuilder` preset builders return a built request
  CHANGELOG.md
  bin/miden-cli/src/commands/new_transactions.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/web-client/src/new_transactions.rs
  docs/src/library.md
  tests/integration/common.rs
  tests/integration/main.rs
  tests/integration/onchain_tests.rs
  tests/integration/swap_transactions_tests.rs
Labels: no docs, bypass-sdk-version-bump

#919 refactor: Move test and stop declaring module from the CLI tests
  .github/workflows/test.yml
  Cargo.toml
  Makefile
  bin/miden-cli/Cargo.toml
  bin/miden-cli/tests/cli.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/node-builder/README.md
  crates/testing/node-builder/examples/simple.rs
  crates/testing/node-builder/src/lib.rs
  crates/testing/node-builder/src/main.rs
  scripts/start-node-bg.sh
Labels: no changelog, no docs

#889 feat: discard subsequent transactions
  CHANGELOG.md
  crates/rust-client/src/sync/state_sync_update.rs
  crates/rust-client/src/transaction/mod.rs
  crates/web-client/package.json
  tests/integration/main.rs
Labels: no docs

#912 feat: Add support for HTTP ACCEPT header version matching
  CHANGELOG.md
  crates/rust-client/src/rpc/tonic_client/api_client.rs
  package.json
Labels: no docs

#881 feat: make network compulsory in init
  bin/miden-cli/src/commands/init.rs
  bin/miden-cli/src/config.rs
  docs/src/cli-reference.md
Labels: no changelog, no docs

#882 refactor: unit test improvements
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/miden-cli/Cargo.toml
  bin/miden-cli/tests/cli.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/mock.rs
  crates/rust-client/src/rpc/domain/transaction.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/test_utils/config/miden-client-rpc.toml
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/test_utils/mod.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/testing/node-builder/examples/simple.rs
  scripts/start-node-bg.sh
  tests/Cargo.toml
  tests/integration/custom_transactions_tests.rs
  tests/integration/fpi_tests.rs
  tests/integration/lib.rs
  tests/integration/main.rs
  tests/integration/onchain_tests.rs
  tests/integration/swap_transactions_tests.rs
Labels: no docs

#925 docs: revise and update documentation in client
  Cargo.lock
  bin/miden-cli/src/faucet_details_map.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/node-builder/src/lib.rs
  docs/src/api-docs.md
  docs/src/cli-config.md
  docs/src/cli-reference.md
  docs/src/design.md
  docs/src/examples.md
  docs/src/features.md
  docs/src/get-started/create-account-use-faucet.md
  docs/src/get-started/p2p-private.md
  docs/src/get-started/p2p-public.md
  docs/src/index.md
  docs/src/install-and-run.md
  docs/src/library.md
  eslint.config.js
Labels: no changelog

#928 feat: add test for network transactions
  Cargo.lock
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/rpc/generated/nostd/note.rs
  crates/rust-client/src/rpc/generated/nostd/requests.rs
  crates/rust-client/src/rpc/generated/nostd/responses.rs
  crates/rust-client/src/rpc/generated/nostd/transaction.rs
  crates/rust-client/src/rpc/generated/std/note.rs
  crates/rust-client/src/rpc/generated/std/requests.rs
  crates/rust-client/src/rpc/generated/std/responses.rs
  crates/rust-client/src/rpc/generated/std/transaction.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/node-builder/src/lib.rs
  tests/integration/onchain_tests.rs
Labels: no changelog, no docs

#926 feat: Add Send + Sync supertraits and add Send to futures return by dyn-compatible traits
  CHANGELOG.md
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/test_utils/mock.rs
Labels: no docs

#937 fix: various CLI issues
  bin/miden-cli/src/commands/sync.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/sqlite_store/transaction.rs
  crates/rust-client/src/store/web_store/transaction/mod.rs
  crates/rust-client/src/store/web_store/transaction/utils.rs
  crates/rust-client/src/sync/state_sync_update.rs
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/transaction/mod.rs
  docs/src/get-started/create-account-use-faucet.md
Labels: no changelog, bypass-sdk-version-bump

#938 refactor: Remove account ID
  bin/miden-cli/src/commands/account.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/commands/notes.rs
  bin/miden-cli/src/faucet_details_map.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/transaction/request/mod.rs
  templates/basic-auth.mct
  templates/basic-fungible-faucet.mct
  tests/integration/main.rs
Labels: no changelog, no docs
