Repository 0xMiden/miden-client, pull requests merged in 2025-06, with the labels that each got.

#945 chore: Move node to next
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/src/commands/new_account.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/store/data_store.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/sync/block_header.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/node-builder/src/lib.rs
  crates/web-client/package-lock.json
  crates/web-client/package.json
  crates/web-client/src/helpers.rs
  crates/web-client/src/models/account_builder.rs
  crates/web-client/src/new_account.rs
  crates/web-client/src/sync.rs
  crates/web-client/test/new_transactions.test.ts
  docs/src/library.md
  docs/src/web-client/api/classes/AccountBuilder.md
  docs/src/web-client/api/classes/FlattenedU8Vec.md
  docs/src/web-client/api/classes/WebClient.md
  tests/Cargo.toml
  tests/integration/fpi_tests.rs
  tests/integration/onchain_tests.rs
Labels: no changelog, no docs

#957 fix: integration test and update dependencies
  Cargo.lock
  tests/integration/main.rs
Labels: no changelog, no docs

#965 Refresh Cargo.lock
  Cargo.lock
Labels: no changelog, no docs

#960 chore(cli): rename miden-cli and miden executable to miden-client-cli and miden-client respectively
  .gitignore
  CHANGELOG.md
  Cargo.lock
  README.md
  bin/miden-cli/Cargo.toml
  bin/miden-cli/README.md
  bin/miden-cli/src/lib.rs
  bin/miden-cli/src/main.rs
  bin/miden-cli/tests/cli.rs
  docs/src/cli-config.md
  docs/src/cli-reference.md
  docs/src/get-started/create-account-use-faucet.md
  docs/src/get-started/p2p-private.md
  docs/src/get-started/p2p-public.md
  docs/src/install-and-run.md
Labels: cli

#966 docs: locked install
  Makefile
  bin/miden-cli/Cargo.toml
  bin/miden-cli/README.md
  crates/rust-client/Cargo.toml
  docs/src/get-started/create-account-use-faucet.md
  docs/src/install-and-run.md
  scripts/start-node-bg.sh
Labels: no changelog

#970 fix: remove `.once` from web test
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/sync/tag.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/web-client/package.json
  crates/web-client/src/models/note.rs
  crates/web-client/src/models/note_tag.rs
  crates/web-client/test/fpi.test.ts
  docs/src/web-client/api/classes/NoteTag.md
  tests/src/custom_transactions_tests.rs
  tests/src/onchain_tests.rs
Labels: no changelog

#897 fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(...)]
  CHANGELOG.md
  bin/miden-cli/src/commands/account.rs
  bin/miden-cli/src/commands/exec.rs
  bin/miden-cli/src/commands/export.rs
  bin/miden-cli/src/commands/import.rs
  bin/miden-cli/src/commands/init.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/commands/new_transactions.rs
  bin/miden-cli/src/commands/notes.rs
  bin/miden-cli/src/commands/sync.rs
  bin/miden-cli/src/commands/tags.rs
  bin/miden-cli/src/commands/transactions.rs
  bin/miden-cli/src/lib.rs
Labels: no docs
