Repository 0xMiden/miden-client, pull requests merged in 2025-08, with the labels that each got.

#1116 feat: reexport `FungibleFaucetExt`
  Cargo.lock
  crates/rust-client/src/account/mod.rs
Labels: no changelog, no docs

#1140 chore: new Rust lints
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/store/note_record/output_note_record/mod.rs
  crates/rust-client/src/store/web_store/account/mod.rs
  crates/rust-client/src/store/web_store/sync/js_bindings.rs
  crates/rust-client/src/tests.rs
  crates/web-client/src/export.rs
Labels: no changelog, no docs, bypass-sdk-version-bump

#1128 refactor: storage and vault Sqlite table refactor
  CHANGELOG.md
  crates/rust-client/src/store/errors.rs
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/store/sqlite_store/store.sql
  crates/rust-client/src/store/sqlite_store/sync.rs
  crates/rust-client/src/store/sqlite_store/transaction.rs
Labels: no docs

#1163 fix: empty map bug
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/store/sqlite_store/store.sql
  crates/rust-client/src/tests.rs
Labels: bug, no changelog, no docs

#1170 feat: remove duplicate error trace
  crates/rust-client/src/errors.rs
Labels: no changelog, no docs

#1175 feat: reexport `Rpo256`
  crates/rust-client/src/lib.rs
Labels: no changelog, no docs

#1111 feat(web-client): add export account method on the web client
  CHANGELOG.md
  bin/miden-cli/src/commands/export.rs
  crates/rust-client/src/keystore/web_keystore.rs
  crates/rust-client/src/utils.rs
  crates/web-client/package.json
  crates/web-client/src/export.rs
  crates/web-client/src/import.rs
  crates/web-client/test/import_export.test.ts
  docs/src/web-client/api/classes/WebClient.md
Labels: no docs

#1202 refactor: RPC errors
  CHANGELOG.md
  bin/integration-tests/src/tests/onchain.rs
  crates/rust-client/src/rpc/errors.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
Labels: no docs

#1180 feat: use playwright instead of puppeteer
  .github/workflows/test.yml
  crates/web-client/.gitignore
  crates/web-client/js/types/index.d.ts
  crates/web-client/package.json
  crates/web-client/playwright.config.ts
  crates/web-client/test/README.md
  crates/web-client/test/account.test.ts
  crates/web-client/test/basic_fungible_faucet_component.test.ts
  crates/web-client/test/fpi.test.ts
  crates/web-client/test/global.test.d.ts
  crates/web-client/test/import.test.ts
  crates/web-client/test/import_export.test.ts
  crates/web-client/test/key.test.ts
  crates/web-client/test/mockchain.test.ts
  crates/web-client/test/new_account.test.ts
  crates/web-client/test/new_transactions.test.ts
  crates/web-client/test/notes.test.ts
  crates/web-client/test/playwright.global.setup.ts
  crates/web-client/test/tags.test.ts
  crates/web-client/test/token_symbol.test.ts
  crates/web-client/test/transactions.test.ts
  crates/web-client/test/webClientTestUtils.ts
  crates/web-client/tsconfig.json
  crates/web-client/yarn.lock
Labels: enhancement, no changelog, web client, no docs

#1196 chore: update `miden-base` to v0.11
  Cargo.lock
  Cargo.toml
  bin/integration-tests/src/tests/network_transaction.rs
  bin/miden-cli/src/commands/account.rs
  crates/rust-client/src/errors.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
Labels: no changelog, no docs

#1209 tests: restore remote prover tests
  crates/web-client/package.json
  crates/web-client/playwright.config.ts
  crates/web-client/test/playwright.global.setup.ts
Labels: no changelog, web client, no docs

#1204 refactor: move `ClientConfig` to integration test binary
  Cargo.lock
  bin/integration-tests/Cargo.toml
  bin/integration-tests/build.rs
  bin/integration-tests/src/main.rs
  bin/integration-tests/src/tests/client.rs
  bin/integration-tests/src/tests/config.rs
  bin/integration-tests/src/tests/custom_transaction.rs
  bin/integration-tests/src/tests/fpi.rs
  bin/integration-tests/src/tests/mod.rs
  bin/integration-tests/src/tests/network_transaction.rs
  bin/integration-tests/src/tests/onchain.rs
  bin/integration-tests/src/tests/swap_transaction.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/test_utils/config.rs
  crates/rust-client/src/test_utils/mod.rs
  crates/rust-client/src/tests.rs
Labels: no changelog, no docs

#1208 docs: update web client docs
  crates/web-client/yarn.lock
  docs/src/web-client/examples/export.md
  docs/src/web-client/examples/import.md
  docs/src/web-client/examples/mock.md
  docs/src/web-client/examples/rpc_client.md
  docs/src/web-client/examples/transactions.md
Labels: no changelog, bypass-sdk-version-bump
