Repository 0xMiden/miden-client, pull requests merged in 2025-07, with the labels that each got.

#998 refactor: remove `TransactionExecutor` from client and note screener
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/src/commands/exec.rs
  bin/miden-cli/src/commands/notes.rs
  bin/miden-cli/src/lib.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/builder.rs
  crates/rust-client/src/errors.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/note/mod.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/rpc/domain/note.rs
  crates/rust-client/src/rpc/errors.rs
  crates/rust-client/src/rpc/generated/nostd/note.rs
  crates/rust-client/src/rpc/generated/nostd/responses.rs
  crates/rust-client/src/rpc/generated/std/note.rs
  crates/rust-client/src/rpc/generated/std/responses.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/sync/mod.rs
  crates/rust-client/src/sync/state_sync.rs
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/testing/node-builder/Cargo.toml
  crates/web-client/package-lock.json
  crates/web-client/src/lib.rs
  crates/web-client/src/models/note.rs
  crates/web-client/src/models/note_script.rs
  crates/web-client/src/models/transaction_script.rs
  crates/web-client/src/transactions.rs
  crates/web-client/test/fpi.test.ts
  crates/web-client/test/new_transactions.test.ts
  crates/web-client/yarn.lock
  docs/src/web-client/api/classes/Note.md
  docs/src/web-client/api/classes/TransactionScript.md
  tests/src/custom_transactions_tests.rs
  tests/src/fpi_tests.rs
  tests/src/main_tests.rs
  tests/src/network_transaction_tests.rs
Labels: no docs, bypass-sdk-version-bump

#950 feat: use remote prover instead of cloning `miden-base`
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  Makefile
  bin/miden-cli/src/commands/init.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/commands/new_transactions.rs
  bin/miden-cli/src/config.rs
  crates/rust-client/Cargo.toml
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/store/sqlite_store/account.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/node-builder/src/lib.rs
  crates/testing/prover/Cargo.toml
  crates/testing/prover/src/main.rs
  crates/web-client/README.md
  crates/web-client/src/helpers.rs
  crates/web-client/src/models/account_builder.rs
  crates/web-client/src/models/account_delta.rs
  crates/web-client/src/new_account.rs
  crates/web-client/test/fpi.test.ts
  crates/web-client/test/new_transactions.test.ts
  crates/web-client/test/transactions.test.ts
  crates/web-client/test/webClientTestUtils.ts
  docs/src/library.md
  docs/src/web-client/api/classes/AccountBuilder.md
  docs/src/web-client/api/classes/AccountDelta.md
  scripts/start-binary-bg.sh
  scripts/start-node-bg.sh
  tests/src/custom_transactions_tests.rs
  tests/src/fpi_tests.rs
  tests/src/main_tests.rs
  tests/src/network_transaction_tests.rs
Labels: no changelog, no docs, bypass-sdk-version-bump

#1017 feat: add transaction script argument support
  CHANGELOG.md
  crates/rust-client/src/transaction/request/builder.rs
  crates/rust-client/src/transaction/request/mod.rs
  tests/src/custom_transactions_tests.rs
Labels: no docs

#1016 refactor: Rename P2IDR references/functions
  CHANGELOG.md
  Makefile
  bin/miden-cli/src/commands/notes.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/web-client/package.json
  crates/web-client/test/notes.test.ts
  crates/web-client/yarn.lock
  tests/src/main_tests.rs
Labels: no docs

#1018 chore: remove `with_` prefix from builder functions
  CHANGELOG.md
  bin/miden-cli/src/commands/new_transactions.rs
  bin/miden-cli/src/lib.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/builder.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/web-client/src/models/transaction_request/transaction_request_builder.rs
  tests/src/custom_transactions_tests.rs
  tests/src/fpi_tests.rs
  tests/src/main_tests.rs
  tests/src/network_transaction_tests.rs
Labels: no docs, bypass-sdk-version-bump

#1001 feat: correct input note order
  CHANGELOG.md
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/web-client/test/new_transactions.test.ts
  tests/src/custom_transactions_tests.rs
  tests/src/main_tests.rs
Labels: no docs, bypass-sdk-version-bump

#1027 refactor: use `into_note_file` in web client
  crates/web-client/package.json
  crates/web-client/src/export.rs
Labels: no changelog, no docs

#1021 ci: Add checks to ci
  .config/nextest.toml
  .github/workflows/lint.yml
  .taplo.toml
  .typos.toml
  CONTRIBUTING.md
  Cargo.toml
  Makefile
  bin/miden-cli/Cargo.toml
  bin/miden-cli/src/commands/export.rs
  bin/miden-cli/src/commands/import.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/commands/sync.rs
  bin/miden-cli/src/faucet_details_map.rs
  bin/miden-cli/tests/files/test_cli_advice_inputs_input.toml
  clippy.toml
  crates/rust-client/Cargo.toml
  crates/rust-client/src/note/mod.rs
  crates/rust-client/src/rpc/domain/note.rs
  crates/rust-client/src/store/web_store/account/mod.rs
  crates/rust-client/src/store/web_store/account/models.rs
  crates/rust-client/src/sync/state_sync.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/test_utils/config/miden-client-rpc.toml
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/builder.rs
  crates/testing/node-builder/Cargo.toml
  crates/testing/prover/Cargo.toml
  crates/web-client/.cargo/config.toml
  crates/web-client/Cargo.toml
  crates/web-client/package.json
  crates/web-client/src/models/account_builder.rs
  crates/web-client/test/README.md
  crates/web-client/yarn.lock
  docs/src/get-started/create-account-use-faucet.md
  docs/src/web-client/examples/transactions.md
  rustfmt.toml
  scripts/check-changelog.sh
  tests/Cargo.toml
  tests/README.md
  tests/src/custom_transactions_tests.rs
  tests/src/main_tests.rs
  tests/src/onchain_tests.rs
  tests/src/swap_transactions_tests.rs
Labels: no changelog, no docs

#1022 Export `ScriptBuilder` from miden-base
  CHANGELOG.md
  bin/miden-cli/src/commands/exec.rs
  bin/miden-cli/src/errors.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/note/mod.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/web-client/src/notes.rs
  crates/web-client/src/transactions.rs
  tests/src/custom_transactions_tests.rs
  tests/src/fpi_tests.rs
Labels: no docs, bypass-sdk-version-bump

#1032 chore: add dependency categories
  Cargo.toml
  bin/miden-cli/Cargo.toml
  crates/rust-client/Cargo.toml
  crates/testing/node-builder/Cargo.toml
  crates/testing/prover/Cargo.toml
  crates/web-client/Cargo.toml
  tests/Cargo.toml
Labels: no changelog, no docs, bypass-sdk-version-bump

#1031 fix: sync notes by user tag
  CHANGELOG.md
  crates/rust-client/src/note/import.rs
  crates/rust-client/src/rpc/mod.rs
  crates/rust-client/src/rpc/tonic_client/mod.rs
  crates/rust-client/src/store/data_store.rs
  crates/rust-client/src/sync/mod.rs
  crates/rust-client/src/sync/state_sync.rs
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/tests.rs
  crates/web-client/package-lock.json
  crates/web-client/package.json
  crates/web-client/src/models/note_script.rs
  crates/web-client/yarn.lock
  docs/src/web-client/api/classes/NoteScript.md
Labels: no docs

#1030 refactor: remove note relevance check from `TransactionResult`
  CHANGELOG.md
  crates/rust-client/src/transaction/mod.rs
Labels: no docs

#1035 fix: final devnet testing
  bin/miden-cli/src/commands/tags.rs
  crates/rust-client/src/note/note_update_tracker.rs
Labels: no changelog, no docs

#1042 feat: introduce enums instead of bool
  CHANGELOG.md
  bin/miden-cli/src/lib.rs
  crates/rust-client/src/builder.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/store/mod.rs
  crates/rust-client/src/store/sqlite_store/chain_data.rs
  crates/rust-client/src/store/sqlite_store/mod.rs
  crates/rust-client/src/store/web_store/chain_data/mod.rs
  crates/rust-client/src/store/web_store/mod.rs
  crates/rust-client/src/sync/block_header.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/mod.rs
  tests/src/main_tests.rs
Labels: no docs, bypass-sdk-version-bump

#1054 chore: update `init` cmd docs
  bin/miden-cli/README.md
  bin/miden-cli/src/commands/init.rs
Labels: no changelog, no docs

#1060 chore: add verbatim_doc_comment in ExecCmd::inputs_path
  bin/miden-cli/src/commands/exec.rs
Labels: no changelog, no docs

#1066 feat: add `hex_to_bytes` utils reexport
  crates/rust-client/src/lib.rs
Labels: no changelog, no docs

#1062 chore: Migrate to `miden-base` rev `dc103637`
  Cargo.lock
  bin/miden-cli/src/commands/account.rs
  bin/miden-cli/src/commands/exec.rs
  bin/miden-cli/src/commands/export.rs
  bin/miden-cli/src/commands/import.rs
  bin/miden-cli/src/commands/new_account.rs
  bin/miden-cli/src/commands/new_transactions.rs
  bin/miden-cli/src/commands/notes.rs
  bin/miden-cli/src/commands/sync.rs
  bin/miden-cli/src/commands/tags.rs
  bin/miden-cli/src/commands/transactions.rs
  bin/miden-cli/src/faucet_details_map.rs
  bin/miden-cli/src/info.rs
  bin/miden-cli/src/lib.rs
  bin/miden-cli/src/utils.rs
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/account/mod.rs
  crates/rust-client/src/account/procedure_roots.rs
  crates/rust-client/src/builder.rs
  crates/rust-client/src/keystore/fs_keystore.rs
  crates/rust-client/src/keystore/web_keystore.rs
  crates/rust-client/src/lib.rs
  crates/rust-client/src/note/import.rs
  crates/rust-client/src/note/mod.rs
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/sync/block_header.rs
  crates/rust-client/src/sync/mod.rs
  crates/rust-client/src/sync/state_sync.rs
  crates/rust-client/src/sync/tag.rs
  crates/rust-client/src/test_utils/common.rs
  crates/rust-client/src/test_utils/mock.rs
  crates/rust-client/src/tests.rs
  crates/rust-client/src/transaction/mod.rs
  crates/rust-client/src/transaction/request/mod.rs
  crates/web-client/src/lib.rs
  crates/web-client/test/fpi.test.ts
  crates/web-client/test/new_transactions.test.ts
  crates/web-client/test/transactions.test.ts
  docs/src/web-client/api/classes/WebClient.md
  tests/src/custom_transactions_tests.rs
  tests/src/fpi_tests.rs
  tests/src/main_tests.rs
  tests/src/network_transaction_tests.rs
Labels: no changelog, no docs

#1051 refactor: insert/commit updates in state sync
  CHANGELOG.md
  crates/rust-client/src/note/note_update_tracker.rs
  crates/rust-client/src/sync/state_sync.rs
  tests/src/main_tests.rs
Labels: no docs

#1081 fix: Avoid passing unneeded nodes to `PartialMmr::from_parts`
  CHANGELOG.md
  Cargo.lock
  crates/rust-client/Cargo.toml
  crates/rust-client/src/sync/block_header.rs
  crates/web-client/Cargo.toml
Labels: no docs

#1089 fix: next build
  crates/rust-client/src/sync/block_header.rs
Labels: no changelog, no docs

#1056 feat(client): make authenticator optional for ClientBuilder and Client
  CHANGELOG.md
  bin/miden-cli/tests/cli.rs
  crates/rust-client/src/builder.rs
  crates/rust-client/src/lib.rs
  crates/web-client/src/lib.rs
  docs/src/library.md
  tests/src/main_tests.rs
Labels: bypass-sdk-version-bump

#1080 refactor: replace `OnNoteReceived` closure with trait
  CHANGELOG.md
  crates/rust-client/src/note/note_screener.rs
  crates/rust-client/src/sync/mod.rs
  crates/rust-client/src/sync/state_sync.rs
Labels: no docs

#1100 feat(web-client): expose more note getters in the web-client
  crates/web-client/src/models/note_inputs.rs
  crates/web-client/src/models/note_recipient.rs
  crates/web-client/src/models/note_script.rs
Labels: no docs, bypass-sdk-version-bump

#1106 ci: bypass docs if sdk bump is ignored
  .github/workflows/web-docs-check.yml
  crates/web-client/package-lock.json
  crates/web-client/yarn.lock
  docs/src/web-client/api/classes/NoteInputs.md
  docs/src/web-client/api/classes/NoteRecipient.md
  docs/src/web-client/api/classes/NoteScript.md
Labels: no changelog, bypass-sdk-version-bump

#1103 fix: cargo-nextest check-tools command
  Makefile
Labels: no changelog, no docs, bypass-sdk-version-bump
